export const SAMPLE_JOURNAL_DATA = {
  '2023-07-01': [
    {
      id: 2,
      name: 'Hanging',
      count: 15,
      date: '2023.7.2',
      time: '12:40pm',
      emotion: 5,
      description: 'Good!',
      color: '#F47C7C',
    },
    {
      id: 3,
      name: 'Band Pull-up',
      count: 20,
      date: '2023.7.2',
      time: '12:40pm',
      emotion: 2,
      description: 'Good!',
      color: '#DFE152',
    },
    {
      id: 4,
      name: 'Muscle-up',
      count: 20,
      date: '2023.7.2',
      time: '12:40pm',
      emotion: 1,
      description: 'Good!',
      color: '#FF8CF4',
    },
  ],
  '2023-07-02': [
    {
      id: 1,
      name: 'Jump Pull-up',
      count: 10,
      date: '2023.7.2',
      time: '12:30pm',
      emotion: 3,
      description: 'Good! I like this exercise so much.',
      color: '#F1B55B',
    },
    {
      id: 2,
      name: 'Hanging',
      count: 15,
      date: '2023.7.2',
      time: '12:40pm',
      emotion: 5,
      description: 'Good!',
      color: '#F47C7C',
    },
    {
      id: 3,
      name: 'Band Pull-up',
      count: 20,
      date: '2023.7.2',
      time: '12:40pm',
      emotion: 2,
      description: 'Good!',
      color: '#DFE152',
    },
    {
      id: 4,
      name: 'Muscle-up',
      count: 20,
      date: '2023.7.2',
      time: '12:40pm',
      emotion: 1,
      description: 'Good!',
      color: '#FF8CF4',
    },
    {
      id: 5,
      name: 'Archer Pull-up',
      count: 20,
      date: '2023.7.2',
      time: '12:40pm',
      emotion: 4,
      description: 'Good!',
      color: '#CD7BFF',
    },
  ],
  '2023-07-03': [
    {
      id: 1,
      name: 'Jump Pull-up',
      count: 10,
      date: '2023.7.3',
      time: '12:30pm',
      emotion: 3,
      description: 'Good! I like this exercise so much.',
      color: '#F1B55B',
    },
    {
      id: 2,
      name: 'Hanging',
      count: 15,
      date: '2023.7.3',
      time: '12:40pm',
      emotion: 5,
      description: 'Good!',
      color: '#F47C7C',
    },
    {
      id: 2,
      name: 'Hanging',
      count: 15,
      date: '2023.7.3',
      time: '12:40pm',
      emotion: 5,
      description: 'Good!',
      color: '#F47C7C',
    },
  ],
  '2023-07-04': [
    {
      id: 4,
      name: 'Muscle-up',
      count: 20,
      date: '2023.7.2',
      time: '12:40pm',
      emotion: 1,
      description: 'Good!',
      color: '#FF8CF4',
    },
    {
      id: 5,
      name: 'Archer Pull-up',
      count: 20,
      date: '2023.7.2',
      time: '12:40pm',
      emotion: 4,
      description: 'Good!',
      color: '#CD7BFF',
    },
    {
      id: 2,
      name: 'Hanging',
      count: 15,
      date: '2023.7.3',
      time: '12:40pm',
      emotion: 5,
      description: 'Good!',
      color: '#F47C7C',
    },
  ],
};
