name: FRONTEND CI/CD

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read

jobs:
  build:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'deploy') && github.base_ref == 'main'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: checkout Github Action
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: npm install
        run: npm ci

      - name: Build project
        run: |
          npm run build --if-present

      - name: init build outputs at AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST}}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo rm -rf /home/ec2-user/github/workspace/build/*
            sudo chown -R ec2-user:ec2-user /home/ec2-user/github/workspace/build
            sudo chmod -R 755 /home/ec2-user/github/workspace/build

      - name: Deploy new build outputs to AWS EC2
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.AWS_HOST}}
          username: ec2-user
          port: 22
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "/home/runner/work/pullanner-web/pullanner-web/build"
          target: "/home/ec2-user"
